import{a as L,i as n,s as w}from"./assets/vendor-BpiDY1p_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const b="46118726-f37cd2f98d2a6e2b7b3af8ac8",P="https://pixabay.com/api/";async function f(o,t){const s=new URLSearchParams({key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});try{const{data:a}=await L(`${P}?${s}`);return a}catch(a){console.log(a),n.error({message:"Something went wrong. Please try again later"})}}function y(o){return o.map(({webformatURL:t,largeImageURL:s,likes:a,views:e,comments:r,downloads:i,tags:p})=>`<li>
  <a href="${s}"><img src="${t}" alt="${p}"><ul>
    <li>Likes ${a}</li>
    <li>Views ${e}</li>
    <li>Comments ${r}</li>
    <li>Downloads ${i}</li>
  </ul></a>
 </li>`).join("")}const g=document.querySelector(".form"),m=document.querySelector(".gallery"),u=document.querySelector(".loader"),d=document.querySelector(".load-more");let c=1,l="";const h=new w(".gallery a");g.addEventListener("submit",S);async function S(o){if(o.preventDefault(),l=o.target.elements.state.value.trim(),console.log(l),c=1,m.innerHTML="",l===""){n.warning({message:"Please enter a search query"});return}u.style.display="block";try{const t=await f(l,c);if(t.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=y(t.hits);m.insertAdjacentHTML("beforeend",s),h.refresh(),t.totalHits>15?d.classList.remove("is-hidden"):d.classList.add("is-hidden")}catch(t){console.log(t),n.error({message:"Something went wrong. Please try again later"})}finally{u.style.display="none",g.reset()}}d.addEventListener("click",q);async function q(){c+=1,u.style.display="block";try{const o=await f(l,c),t=y(o.hits);m.insertAdjacentHTML("beforeend",t),h.refresh(),Math.ceil(o.totalHits/15)===c?(d.classList.add("is-hidden"),n.info({message:"We're sorry, but you've reached the end of search results."})):d.classList.remove("is-hidden")}catch(o){console.log(o),n.error({message:"Something went wrong. Please try again later"})}finally{u.style.display="none"}}
//# sourceMappingURL=index.js.map
